/****** Object:  Database [SmootWebsite]    Script Date: 12/19/2020 6:58:04 PM ******/
CREATE DATABASE [SmootWebsite]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 2 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [SmootWebsite] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmootWebsite] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmootWebsite] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmootWebsite] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmootWebsite] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmootWebsite] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmootWebsite] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmootWebsite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmootWebsite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmootWebsite] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmootWebsite] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmootWebsite] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmootWebsite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmootWebsite] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [SmootWebsite] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmootWebsite] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SmootWebsite] SET  MULTI_USER 
GO

ALTER DATABASE [SmootWebsite] SET ENCRYPTION ON
GO

ALTER DATABASE [SmootWebsite] SET QUERY_STORE = ON
GO

ALTER DATABASE [SmootWebsite] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO

ALTER DATABASE [SmootWebsite] SET  READ_WRITE 
GO

